# Generated by Django 6.1 on 2026-08-19 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='claimant',
            field=models.ForeignKey(help_text='المستخدم الذي يدّعي ملكية الغرض', on_delete=django.db.models.deletion.CASCADE, related_name='claimed_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
