# Generated by Django 6.1 on 2026-08-19 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_claimant'),
        ('reports', '0003_alter_category_options_alter_report_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'محادثة', 'verbose_name_plural': 'المحادثات'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'رسالة', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='claimant',
            field=models.ForeignKey(help_text='المستخدم الذي يدّعي ملكية الغرض', on_delete=django.db.models.deletion.CASCADE, related_name='claimed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='المدّعي'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reports.report', verbose_name='الإعلان'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='المحادثة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
    ]
