# Generated by Django 5.2.17 on 2026-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ownership_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الملكية'),
        ),
    ]
