# Generated by Django 5.2.17 on 2026-08-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(blank=True, choices=[('desktop', 'كمبيوتر'), ('mobile', 'جوال'), ('tablet', 'تابلت'), ('other', 'أخرى')], max_length=10),
        ),
    ]
