# Generated by Django 6.1 on 2026-08-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name_ar'], 'verbose_name': 'مدينة', 'verbose_name_plural': 'المدن'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_ar'], 'verbose_name': 'دولة', 'verbose_name_plural': 'الدول'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='رمز الدولة'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
    ]
