# Generated by Django 5.2.17 on 2026-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
