# Generated by Django 6.1 on 2026-08-19 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class, e.g. bi-wallet2', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'مفقود'), ('found', 'معثور عليه')], max_length=5)),
                ('status', models.CharField(choices=[('open', 'قائم'), ('resolved', 'تم الاسترجاع')], default='open', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_details', models.CharField(blank=True, help_text='مكان الفقدان/العثور بالتفصيل', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('event_date', models.DateField(help_text='تاريخ الفقدان أو العثور')),
                ('verification_question', models.CharField(blank=True, help_text='سؤال يستخدم للتأكد من ملكية الحاجة قبل التسليم (يظهر لصاحب البلاغ فقط)', max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='locations.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.country')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
