# Generated by Django 6.1 on 2026-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='verification_question',
            field=models.CharField(blank=True, help_text='سؤال يُستخدم للتحقق من ملكية الغرض قبل التسليم (يظهر لصاحب البلاغ فقط)', max_length=255),
        ),
    ]
