# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_add_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name_ar'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='نسبة التطابق')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب التطابق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('found_report', models.ForeignKey(limit_choices_to={'type': 'found'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='reports.report', verbose_name='الإعلان المعثور عليه')),
                ('lost_report', models.ForeignKey(limit_choices_to={'type': 'lost'}, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='reports.report', verbose_name='الإعلان المفقود')),
            ],
            options={
                'verbose_name': 'تطابق محتمل',
                'verbose_name_plural': 'التطابقات المحتملة',
                'ordering': ['-score'],
                'unique_together': {('lost_report', 'found_report')},
            },
        ),
    ]
