# Generated by Django 5.2.17 on 2026-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_category_options_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='identifier',
            field=models.CharField(blank=True, help_text='رقم مميز للغرض إن وجد، مثل الرقم التسلسلي للإلكترونيات أو رقم المستند للوثائق. غير إجباري، لكنه يسهّل البحث والتأكد من الملكية.', max_length=100, verbose_name='رقم المعرف'),
        ),
    ]
