# Generated by Django 5.2.17 on 2026-08-20 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تذكير'),
        ),
        migrations.CreateModel(
            name='ReportFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('offensive', 'محتوى مسيء أو غير لائق'), ('misleading', 'معلومات مضللة أو غير صحيحة'), ('duplicate', 'إعلان مكرر'), ('other', 'سبب آخر')], max_length=20, verbose_name='السبب')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('resolved', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reports.report', verbose_name='الإعلان')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_flags', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم البلاغ')),
            ],
            options={
                'verbose_name': 'إبلاغ عن إعلان',
                'verbose_name_plural': 'بلاغات الإعلانات',
                'ordering': ['-created_at'],
                'unique_together': {('report', 'reporter')},
            },
        ),
    ]
