# Generated by Django 5.2.17 on 2026-08-20 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('match', 'تطابق محتمل'), ('message', 'رسالة جديدة'), ('resolved_reminder', 'تذكير بالاسترجاع')], max_length=20, verbose_name='النوع')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='التفاصيل')),
                ('url', models.CharField(max_length=300, verbose_name='الرابط')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
