# Generated by Django 5.2.17 on 2026-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match', 'تطابق محتمل'), ('message', 'رسالة جديدة'), ('resolved_reminder', 'تذكير بالاسترجاع'), ('rating', 'تقييم جديد')], max_length=20, verbose_name='النوع'),
        ),
    ]
